import re
from nltk.corpus import wordnet as wn

#Function that uses regex to assign the correct plural suffix to a noun
def plural(noun):
	if re.search('[sxz]$', noun):
		return re.sub('$', 'es', noun)
	elif re.search('[^aeioudgkprt]h$', noun):
		return re.sub('$', 'es', noun)
	elif re.search('[^aeiou]y$', noun):
		return re.sub('y$', 'ies', noun)
	else:
		return noun + 's'

header = ''' /* 
	Klemen Kotar, CSE 341, Secion AA, Homework 5 - Prolog Warmup Complete Sentence Generator
	
	Prolog file that generates every possible English sentence consisting of
	an adjective, a plural noun and a verb (Disclaimer: Most sentences do not make sense)

	Generated by a python script using the nltk corpus
*/

/* Problem 2 - sentence */
sentence(A,N,V) :-
    adjective(A),
    noun(N),
    verb(V).

/* Definitions for adjectives, nouns and verbs */
'''

f = open("all_sentences.pl","w+")
f.write(header)

for synset in list(wn.all_synsets('a')):
	s = "adjective(" + synset.name()[0:-5].replace(".", "_").replace("'", "_") + ").\n"
	f.write(s)

for synset in list(wn.all_synsets('n')):
	s = "noun(" + plural(synset.name()[0:-5].replace(".", "_").replace("'", "_")) + ").\n"
	f.write(s)

for synset in list(wn.all_synsets('v')):
	s = "verb(" + synset.name()[0:-5].replace(".", "_").replace("'", "_") + ").\n"
	f.write(s)

f.write("/* End of File */")
